const NAVIGATION = [
  {
    key: 0,
    label: 'HOME',
    link: '/',
    fn: null,
  },
  {
    key: 1,
    label: 'PRODUCTS',
    link: '/products',
    fn: null,
  },
  {
    key: 2,
    label: 'SERVICES',
    link: '/services',
    fn: null,
  },
  {
    key: 3,
    label: 'NEWS',
    link: '/news',
    fn: null,
  },
  {
    key: 4,
    label: 'CONTACT',
    link: '/contact',
    fn: null,
  },
];

const OFFICES = [
  {
    description: 'Head Office - Factory',
    name: 'FutureCard Industries LLC',
    address: '420, University City Road',
    subAddress: 'Industrial Area 13',
    zipCode: '',
    poBox: '150199',
    city: 'Sharjah',
    country: 'UAE',
    telephone: '+971 6 538 9488',
    fax: '+971 6 558 3707​',
    email: 'info@futurecard.com',
  },
  {
    description: 'Middle East - CIS - APAC',
    name: 'FutureCard Dubai',
    address: 'Opal Tower, Burj Khalifa St.',
    subAddress: 'Business Bay',
    zipCode: '1004',
    poBox: '9051',
    city: 'Dubai',
    country: 'UAE',
    telephone: '+971 4 361 5997',
    fax: '+971 4 361 9255',
    email: 'info@futurecard.com',
  },
  {
    description: 'Europe - North America',
    name: 'FutureCard - France',
    address: '13, rue Camille Desmoulins',
    subAddress: '',
    zipCode: '92130',
    poBox: '',
    city: 'Issy-les-Moulineaux',
    country: 'France',
    telephone: '+33 1 58 04 26 92',
    fax: '',
    email: 'info@futurecard.com',
  },
  {
    description: 'Iberia - LATAM',
    name: 'FutureCard - Spain',
    address: 'c/Alcalá 20',
    subAddress: '',
    zipCode: '28014',
    poBox: '',
    city: 'Madrid',
    country: 'Spain',
    telephone: '+34 9 15 22 07 90',
    fax: '+34 9 15 22 07 89',
    email: 'info@futurecard.com',
  },
  {
    description: 'Africa',
    name: 'FutureCard - South Africa',
    address: 'Cresta 2118',
    subAddress: '',
    zipCode: '28014',
    poBox: '644',
    city: 'Johannesburg',
    country: 'South Africa',
    telephone: '+34 9 15 22 07 90',
    fax: '+27 11 791 6675',
    email: 'info@futurecard.com',
  },
];

export { NAVIGATION, OFFICES };
